---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>

# Runs on tag push, promotes draft release
name: 'Release on Tag Push ðŸš€'

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      # Triggered only by semantic tags push
      - '**'

permissions: {}

jobs:
  promote-release:
    name: 'Promote Draft Release'
    # yamllint disable-line rule:line-length
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a  # v2.13.1
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: 'Verify Pushed Tag'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/tag-push-verify-action@80e2bdbbb9ee7b67557a31705892b75e75d2859e  # v0.1.1
        with:
          versioning: 'semver'

      - name: 'Promote draft release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/draft-release-promote-action@cd7cf442875ecaea5dbb070d0de94f21ece107c8  # v0.1.3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ github.ref_name }}"
          latest: true
